
GET https://hqfq6pwuqf.execute-api.ap-southeast-1.amazonaws.com/timeslots/169312/2021-08-05
content-type: application/json
###
 
 GET https://hqfq6pwuqf.execute-api.ap-southeast-1.amazonaws.com/timeslots/169312
content-type: application/json
 
 




###
POST https://hqfq6pwuqf.execute-api.ap-southeast-1.amazonaws.com/timeslots  
content-type: application/json

{
    "entityId": "1111",
    "dateList": [ "2021-10-12"],
    "timeslots" : { 
        "1000-1100" :400,
        "1100-1200" :400,
        "1200-1300" :400,
        "1300-1400" :400,
        "1400-1500" :400,
        "1500-1600" :400,
        "1600-1700" :400
    }
}
 
###

GET https://hqfq6pwuqf.execute-api.ap-southeast-1.amazonaws.com/timeslots?date=0001-01-01
content-type: application/json


###
PUT https://hqfq6pwuqf.execute-api.ap-southeast-1.amazonaws.com/timeslots
content-type: application/json
Authorization: bearer niceloop

{
	"entityId": "0000",
	"date": "0001-01-01",
	"time": "0000-0100",
	"action": "remove",
    "value" : 5
}
 
 # remove,  open , active