POST https://hqfq6pwuqf.execute-api.ap-southeast-1.amazonaws.com/users  
content-type: application/json
Authorization: bearer eyJraWQiOiIwZjdhYzBmOGEyMmUxMzFiNWZlNzVhOWNlMTY5OWFjYTE1MGY3ZjZjMGVkNzVlMjgyYjNiZjdmYjA5N2E3NjNlIiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJodHRwczovL2FjY2Vzcy5saW5lLm1lIiwic3ViIjoiVTI3OTU3ZTEzNjIxOTQwYjcyYzcwMTg1NWIzZmRlNmE1IiwiYXVkIjoiMTY1NjI1NzM0NyIsImV4cCI6MTYyNzYyMTI5NywiaWF0IjoxNjI3NjE3Njk3LCJhbXIiOlsibGluZXNzbyJdLCJuYW1lIjoidXRwIiwicGljdHVyZSI6Imh0dHBzOi8vcHJvZmlsZS5saW5lLXNjZG4ubmV0LzBoT3pIdGJISmxFRlYxRFRua041ZHZBa2xJSGpnQ0l4WWREV3hZTjFFS0cyRlFQUWNFSFR4ZU93QUZHMlJRYlZkVVREZ01ZUU1GUm13SSJ9.XOo2zEeSflwJH06gHN9a7_bJnpx3vr1IeP5HF_55-dWoB-EDm_jXMgl5X1_k4VLEPIEPBYOCzpJ_UEGMyBozDg

{
    "uid": "000000",
    "name" : "rice"
}